# 路径点

geometry_msgs/PoseStamped pose  # 位置和航向
float64 s                       # s
float64 l                       # l
float64 ds_dt                   # ds/dt
float64 dl_ds                   # l'
float64 dl_dt                   # dl_dt
float64 dds_dt                  # dds/dt
float64 ddl_ds                  # l''
float64 ddl_dt                  # ddl_dt
float64 theta                   # 航向角
float64 kappa                   # 曲率
float64 dkappa                  # 曲率变化率
float64 rs                      # 作为投影点的rs
float64 rtheta                  # 作为投影点的航向角
float64 rkappa                  # 作为投影点的曲率
float64 rdkappa                 # 作为投影点的曲率变化率